### ISSUE TITLE
License

### ISSUE THREAD

**Issue by skogsbrus** [asg017/sqlite-vec#1]
Hi there, 

Found this repo from your [blog post](https://alexgarcia.xyz/blog/2024/building-new-vector-search-sqlite/index.html). Sounds like a very fun project!

Have you given any thoughts to what license you'll use yet?

If you're looking for contributors, I'd be interested too :)

**Comment by asg017** [comment]
Will definitely be MIT, maybe dual-license with Apache-2!

And thanks for the contribution offer! For now there won't be much to code to contribute to until `v0.1.0` in a few weeks, but will definitely be opportunities down the road! And as always, trying out + giving feedback is always appreciated!

**Comment by asg017** [comment]
MIT + Apache-2 licenses added
