### ISSUE TITLE
linux-aarch64 support

### ISSUE THREAD

**Issue by amirmolavi** [asg017/sqlite-vec#131]
I am trying to install   sqlite-vec via pixi on a linux-aarch64 platform and it fails 

x failed to solve the pypi requirements of 'notebooks' 'linux-aarch64'
  |-> failed to resolve pypi dependencies
  `-> Because sqlite-vec==0.1.3 has no wheels with a matching platform tag
      and only sqlite-vec<=0.1.3 is available, we can conclude that sqlite-
      vec>=0.1.3 cannot be used.
      And because you require sqlite-vec>=0.1.3, we can conclude that your
      requirements are unsatisfiable.
      
      hint: Pre-releases are available for sqlite-vec in the requested
      range (e.g., 0.1.4a2), but pre-releases weren't enabled (try:
      `--prerelease=allow`)

**Comment by acmiyaguchi** [comment]
Issue #110 seems to be related too. I've personally been running into issues trying to install the package on an macbook air m1 inside of docker (arm image). 

```
9.963   Unable to find installation candidates for sqlite-vec (0.1.3)
9.964 
9.964   at /usr/local/lib/python3.11/site-packages/poetry/installation/chooser.py:74 in choose_for
9.970        70│ 
9.970        71│             links.append(link)
9.970        72│ 
9.970        73│         if not links:
9.970     →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
9.970        75│ 
9.970        76│         # Get the best link
9.970        77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
9.970        78│ 
9.970 
9.970 Cannot install sqlite-vec.
```

**Comment by acmiyaguchi** [comment]
I wonder if the cosmopolitan builds could be used for aarch64. It looks like the biggest limitation to arm builds is that github doesn't support arm runners generally at the moment.

**Comment by asg017** [comment]
Forgot to mention: as of [`v0.1.6`](https://github.com/asg017/sqlite-vec/releases/tag/v0.1.6) there are official Linux arm/aarch64 builds of `sqlite-vec` available.

Here's a direct link if you'd like to test: https://github.com/asg017/sqlite-vec/releases/download/v0.1.6/sqlite-vec-0.1.6-loadable-linux-aarch64.tar.gz

Please let me know if you have any issues with it, otherwise I'll close this issue for now.

**Comment by luca3m** [comment]
thanks @asg017 for the update!

I'm trying to pull it in my Ruby project but it does not find it:

```
Fetching gem metadata from https://rubygems.org/.........
Could not find gems matching 'sqlite-vec' valid for all resolution platforms (arm64-darwin, x86_64-darwin, x86_64-linux, x86_64-linux-gnu, x86_64-linux-musl,
aarch64-linux, arm64-darwin-24) in rubygems repository https://rubygems.org/ or installed locally.

The source contains the following gems matching 'sqlite-vec':

... cut

  * sqlite-vec-0.1.6-arm64-darwin
  * sqlite-vec-0.1.6-arm64-linux
  * sqlite-vec-0.1.6-x86_64-darwin
  * sqlite-vec-0.1.6-x86_64-linux
  * sqlite-vec-0.1.6-x86_64-mingw32
```

It seems `bundle` expects to find aarch64-linux instead of arm64-linux.

**Comment by marko911** [comment]
> Forgot to mention: as of [`v0.1.6`](https://github.com/asg017/sqlite-vec/releases/tag/v0.1.6) there are official Linux arm/aarch64 builds of `sqlite-vec` available.
> 
> Here's a direct link if you'd like to test: https://github.com/asg017/sqlite-vec/releases/download/v0.1.6/sqlite-vec-0.1.6-loadable-linux-aarch64.tar.gz
> 
> Please let me know if you have any issues with it, otherwise I'll close this issue for now.

if you do `file vec0.so` on that package ,
it returns
`vec0.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=126100873b8858013bd396b329eccfa35f27acf5, not stripped`
