### ISSUE TITLE
Question: How should I import vector files using sqlite-vec

### ISSUE THREAD

**Issue by XiuTsong** [asg017/sqlite-vec#15]
The README says that "vectors can be provided as JSON or in a compact binary format." However, I have attempted many times to import .json files using the ".import" command without success, encountering an error at `vector_from_value`.

Could you instruct me on the correct method for importing files? For instance, if I wish to write the following data, what should the JSON file look like?

```
insert into vec_examples(rowid, sample_embedding)
  values
    (1, '[-0.200, 0.250, 0.341, -0.211, 0.645, 0.935, -0.316, -0.924]'),
    (2, '[0.443, -0.501, 0.355, -0.771, 0.707, -0.708, -0.185, 0.362]'),
    (3, '[0.716, -0.927, 0.134, 0.052, -0.669, 0.793, -0.634, -0.162]'),
    (4, '[-0.710, 0.330, 0.656, 0.041, -0.990, 0.726, 0.385, -0.958]');
```

**Comment by XiuTsong** [comment]
Oh, I have found that I can use ".read" command instead, which can solve the problem.

**Comment by asg017** [comment]
Not sure if the `.read` command would help here. If you have a JSON file of an array of vectors (ie `[ [1,2, ...], [3, 4, ...] ]`, and you're using the SQLite CLI, use a combination of [`readfile`](https://sqlite.org/cli.html#:~:text=The%20readfile) and [`json_each`](https://sqlite.org/json1.html#jeach) like so:


```sql
create virtual table vec_examples( sample_embedding[128]);

insert into vec_examples(rowid, sample_embedding)
  select rowid, value
  from json_each(readfile('my_file.json'));

```
