### ISSUE TITLE
Quick Question: Code formatter? 

### ISSUE THREAD

**Issue by dleviminzi** [asg017/sqlite-vec#22]
Hey there!

What code formatter are you using? I'm looking to use the same one as I work that way I don't have to keep manually matching.

**Comment by asg017** [comment]
`clang-format`, and there's a `make format` command that runs it (and also `black` on the python tests). 

Though I have no idea how `clang-format` works across machines, it's just the first one that came up when I googled "c formatter". If you notice any discrepancies let me know, I can add a config file if it's not matching

**Comment by dleviminzi** [comment]
> `clang-format`, and there's a `make format` command that runs it (and also `black` on the python tests). 
> 
> 
> 
> Though I have no idea how `clang-format` works across machines, it's just the first one that came up when I googled "c formatter". If you notice any discrepancies let me know, I can add a config file if it's not matching

Doh don't know how I missed that in the Makefile 😅

Thank you!
