### ISSUE TITLE
Broken curl links in install.sh file of v0.0.1-alpha.14 release

### ISSUE THREAD

**Issue by Jon-Biz** [asg017/sqlite-vec#36]
There's a 'v' missing from the version numbers in the file names.

install.sh:
```
https://github.com/asg017/sqlite-vec/releases/download/0.0.1-alpha.14/sqlite-vec-0.0.1-alpha.14-loadable-macos-x86_64.tar.gz
```
Actual release file link:
```
https://github.com/asg017/sqlite-vec/releases/download/v0.0.1-alpha.14/sqlite-vec-0.0.1-alpha.14-loadable-macos-x86_64.tar.gz
```

**Comment by asg017** [comment]
Thanks for reporting!

Should now be fixed in `v0.0.1-alpha.16`: https://github.com/asg017/sqlite-vec/releases/download/v0.0.1-alpha.16/install.sh

Let me know if you run into any other issues!
