### ISSUE TITLE
SELECT ERROR

### ISSUE THREAD

**Issue by oldmanpushcart** [asg017/sqlite-vec#41]
Hi, I'm try using sqlite-vec, follow the README guide.

```SQL
select
  rowid,
  distance
from vec_examples
where sample_embedding match '[0.890, 0.544, 0.825, 0.961, 0.358, 0.0196, 0.521, 0.175]'
order by distance
limit 2;
```

 but I got an error.

```
ERROR: A LIMIT or 'k = ?' constraint is required on vec0 knn queries.
```

I need some help, thank you~

**Comment by asg017** [comment]
Hey thanks for filing - this is a bug with the SQLite version you're using. TL:DR try this:

```sql
select
  rowid,
  distance
from vec_examples
where sample_embedding match '[0.890, 0.544, 0.825, 0.961, 0.358, 0.0196, 0.521, 0.175]'
  and k = 2
order by distance;
```

The `limit 2` syntax only works on SQLite version 3.41 and above, but the `k = 2` syntax should work on older versions. You could also upgrade the version of SQLite you're using, but that may be more difficult. 

I'll leave this issue open until I improve the error message

**Comment by oldmanpushcart** [comment]
Create! It works !! thank you for your reply~

**Comment by v-yunbin** [comment]
how to install a python SQLite version 3.41?

**Comment by v-yunbin** [comment]
my sqlite_version=3.41.2, vec_version=v0.1.1 but it not work with follows codes:
```
      SELECT
        vec_sentences.id,
        distance,
        sentence
      FROM vec_sentences
      LEFT JOIN sentences ON sentences.id = vec_sentences.id
      WHERE sentence_embedding MATCH ?
      ORDER BY distance
      limit 3;
```
still get follows errors:
```
Traceback (most recent call last):
  File "query.py", line 27, in <module>
    results = db.execute(
sqlite3.OperationalError: A LIMIT or 'k = ?' constraint is required on vec0 knn queries.
```

**Comment by asg017** [comment]
@v-yunbin can you try:

```sql
      SELECT
        vec_sentences.id,
        distance,
        sentence
      FROM vec_sentences
      LEFT JOIN sentences ON sentences.id = vec_sentences.id
      WHERE sentence_embedding MATCH ?
        AND k = 3
      ORDER BY distance;
```

Or possibly upgrade sqlite to >=3.42, I might be wrong about it working on 3.41
