### ISSUE TITLE
fails in server-side nextjs app with bad path argument

### ISSUE THREAD

**Issue by tobowers** [asg017/sqlite-vec#82]
I installed by nextjs app with Bun and I tried both `bun run dev` and `npm run dev` but got the same error when trying to do sqlitevec.load:

`The "path" argument must be of type string or an instance of URL. Received an instance of URL`

Minimal code:

import "server-only";

import Database from 'better-sqlite3';
import * as sqliteVec from "sqlite-vec";

export const getDatabase = (path: string) => {
  const db = new Database(path);
  // db.pragma('journal_mode = WAL');
  sqliteVec.load(db);
  const { vec_version } = db.prepare("select vec_version() as vec_version;").get() as any;
  console.log(`vec_version=${vec_version}`);

  return db;
} 

This was run in a nextjs app server rending, so I assume everything went through webpack.

**Comment by asg017** [comment]
Can you give more info when that error is thrown? Is it during the `sqliteVec.load()` line, or before? 

I'm not familiar with next.js, but is it bundling your JS code and executing that separately from `node_modules`? The `sqlite-vec` npm package expects the `node_modules` folder to contain the compiled extension, so if nextjs bundles your code and executes it separately you may need to change a few things. A reproducible example/repo would be extremely helpful

**Comment by tobowers** [comment]
Here you go - this is a minimal repo https://github.com/tobowers/minimal-failing-sql-vec-nextjs/blob/main/src/app/page.tsx#L5-L13

**Comment by asg017** [comment]
@tobowers can you bump to `v0.1.2-alpha.6` and try again? Next.js/webpack mangles URLs [[according to this](https://github.com/vercel/next.js/issues/55523) and the latest release should fix it

**Comment by tobowers** [comment]
Seems to be working! Thanks!
