### ISSUE TITLE
How to bind the foreign key?

### ISSUE THREAD

**Issue by fayfive** [asg017/sqlite-vec#86]
For example
```sql
CREATE TABLE person (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    addr TEXT,
    gender TEXT
);
```
And How to bind the foreign key to vec0, I want to delete the vec0 when I delete person.
Thanks!

**Comment by asg017** [comment]
I don't believe there's a way to do this with virtual tables, but you can setup a [trigger](https://www.sqlite.org/lang_createtrigger.html) like so:


```sql
CREATE TABLE person (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    addr TEXT,
    gender TEXT
);
CREATE VIRTUAL TABLE vec_person USING vec0(
  id integer primary key,
  embedding float[888]
);

CREATE TRIGGER person_ad AFTER DELETE ON person BEGIN
  DELETE FROM vec_person WHERE id = old.id;
END;

```

**Comment by fayfive** [comment]
Thanks for your reply.
I'm not  familiar with virtual table.

**Comment by mholt** [comment]
Thanks @asg017 for the answer, and @fayfive  for the question -- this helped me too!
