### ISSUE TITLE
Add Extern C for cpp project

### ISSUE THREAD

**Issue by Adriankhl** [asg017/sqlite-vec#9]
Hi, thanks for the library, it really suit my need to have a vector db on both Windows, Linux and Android and I am already trying it in [my project](https://github.com/Adriankhl/godot-llm/).

Just a small request. Can you add `extern "C"` for `#ifdef __cplusplus` in the header file so that I don't have to manually do it for my cpp project?

**Comment by asg017** [comment]
No problem! Just published [`v0.0.1-alpha.10`](https://github.com/asg017/sqlite-vec/releases/tag/v0.0.1-alpha.10) which added the `extern "C" {` guard. Let me know if it works!

And thanks for sharing your project, looks super interesting! LLM-powered NPCs sounds super cool, will definitely follow!
