### ISSUE TITLE
(Question) Is the data persistent?

### ISSUE THREAD

**Issue by igorcafe** [asg017/sqlite-vec#95]
It seems to me that this library works per session.
When I reload the program and I run `SELECT COUNT(*)` it gives me 0.

Are the vectors being stored in RAM only?

**Comment by asg017** [comment]
Vectors should persist. A few questions:

- Are you storing the database into a file, or are you using a `:memory:` SQLite database? 
- Are you committing results after inserting data? Ex are you running `db.commit()` at the end of the program?

As always, if you can share a code sample of what you're seeing, that would also help debug any issues.

**Comment by igorcafe** [comment]
probably my mistake... just wanted be sure the virtual table is not RAM only.
thanks!
